In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('../dataset/IMDB Dataset.csv')

In [4]:
print(df.shape)
df.head()

(50000, 2)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [8]:
df['review'] = df['review'].str.lower()

In [9]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [11]:
## Remove html tags
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [12]:
sample = "<html><body><h1>Hello World</h1></body></html>"

print(remove_html_tags(sample))

Hello World

In [13]:
df['review'] = df['review'].apply(remove_html_tags)

In [14]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [15]:
## Remove URL
def remove_url(text):
    pattern = re.compile(r'http\S+|www\S+')
    return pattern.sub(r'', text)

In [16]:
text1 = "Visit https://www.google.com for searching information."

text2 = "Watch tutorials at https://www.youtube.com/watch?v=abc123"

text3 = "My website is www.ashishkumar.com and it contains projects."

text4 = "Check both https://github.com and www.kaggle.com for learning."

text5 = "This movie is amazing! More details at https://www.imdb.com/title/tt0111161/"

In [17]:
print(remove_url(text1))
print(remove_url(text2))
print(remove_url(text3))
print(remove_url(text4))
print(remove_url(text5))

Visit  for searching information.
Watch tutorials at
My website is  and it contains projects.
Check both  and  for learning.
This movie is amazing! More details at

In [18]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [19]:
exclude = string.punctuation

In [20]:
def remove_punctuation(text):
    for char in exclude:
        text = text.replace(char, '')
    return text

In [22]:
text = "Hello!!! How are you?"
start_time = time.time()
print(remove_punctuation(text))
end_time = time.time()
print(f"Execution time: {end_time - start_time} seconds")

Hello How are you
Execution time: 0.000469207763671875 seconds

In [29]:
def remove_punctuation1(text):
    return text.translate(str.maketrans('', '', exclude))

In [30]:
text = "Hello!!! How are you?"
start_time = time.time()
print(remove_punctuation1(text))
end_time = time.time()
print(f"Execution time: {end_time - start_time} seconds")

Hello How are you
Execution time: 0.00017333030700683594 seconds

In [31]:
## chat word treatment
chat_words = {
    "u": "you",
    "ur": "your",
    "r": "are",
    "b4": "before",
    "gr8": "great",
    "luv": "love",
    "thx": "thanks",
    "ty": "thank you",
    "pls": "please",
    "plz": "please",
    "msg": "message",
    "btw": "by the way",
    "idk": "i do not know",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "brb": "be right back",
    "gtg": "got to go",
    "ttyl": "talk to you later",
    "omg": "oh my god",
    "lol": "laughing out loud",
    "lmao": "laughing my ass off",
    "rofl": "rolling on the floor laughing",
    "fyi": "for your information",
    "asap": "as soon as possible",
    "np": "no problem",
    "nvm": "never mind",
    "tbh": "to be honest",
    "wfh": "work from home",
    "afaik": "as far as i know",
    "ikr": "i know right",
    "smh": "shaking my head",
    "wyd": "what are you doing",
    "wbu": "what about you",
    "gm": "good morning",
    "gn": "good night",
    "tc": "take care",
    "ily": "i love you",
    "ilysm": "i love you so much",
    "hru": "how are you",
    "cu": "see you",
    "cya": "see you",
    "bcz": "because",
    "bcuz": "because",
    "coz": "because",
    "abt": "about",
    "bday": "birthday",
    "atm": "at the moment",
    "bff": "best friend forever",
    "bf": "boyfriend",
    "gf": "girlfriend",
    "dm": "direct message",
    "faq": "frequently asked questions",
    "fb": "facebook",
    "ig": "instagram",
    "yt": "youtube",
    "irl": "in real life",
    "jk": "just kidding",
    "k": "okay",
    "kk": "okay",
    "lmk": "let me know",
    "omw": "on my way",
    "ppl": "people",
    "rn": "right now",
    "sry": "sorry",
    "tmrw": "tomorrow",
    "txt": "text",
    "wknd": "weekend",
    "xoxo": "hugs and kisses",
    "ya": "you",
    "yup": "yes",
    "nah": "no",
    "fav": "favorite",
    "sec": "second",
    "mins": "minutes",
    "congrats": "congratulations",
    "gonna": "going to",
    "wanna": "want to",
    "gotta": "got to",
    "lemme": "let me",
    "tho": "though",
    "thru": "through",
    "yolo": "you only live once",
    "fomo": "fear of missing out",
    "tgif": "thank god it's friday",
    "wtf": "what the fuck",
    "wth": "what the hell",
    "idc": "i do not care"
}

In [32]:
chat_words

{'u': 'you',
 'ur': 'your',
 'r': 'are',
 'b4': 'before',
 'gr8': 'great',
 'luv': 'love',
 'thx': 'thanks',
 'ty': 'thank you',
 'pls': 'please',
 'plz': 'please',
 'msg': 'message',
 'btw': 'by the way',
 'idk': 'i do not know',
 'imo': 'in my opinion',
 'imho': 'in my humble opinion',
 'brb': 'be right back',
 'gtg': 'got to go',
 'ttyl': 'talk to you later',
 'omg': 'oh my god',
 'lol': 'laughing out loud',
 'lmao': 'laughing my ass off',
 'rofl': 'rolling on the floor laughing',
 'fyi': 'for your information',
 'asap': 'as soon as possible',
 'np': 'no problem',
 'nvm': 'never mind',
 'tbh': 'to be honest',
 'wfh': 'work from home',
 'afaik': 'as far as i know',
 'ikr': 'i know right',
 'smh': 'shaking my head',
 'wyd': 'what are you doing',
 'wbu': 'what about you',
 'gm': 'good morning',
 'gn': 'good night',
 'tc': 'take care',
 'ily': 'i love you',
 'ilysm': 'i love you so much',
 'hru': 'how are you',
 'cu': 'see you',
 'cya': 'see you',
 'bcz': 'because',
 'bcuz': 'because',
 'coz': 'because',
 'abt': 'about',
 'bday': 'birthday',
 'atm': 'at the moment',
 'bff': 'best friend forever',
 'bf': 'boyfriend',
 'gf': 'girlfriend',
 'dm': 'direct message',
 'faq': 'frequently asked questions',
 'fb': 'facebook',
 'ig': 'instagram',
 'yt': 'youtube',
 'irl': 'in real life',
 'jk': 'just kidding',
 'k': 'okay',
 'kk': 'okay',
 'lmk': 'let me know',
 'omw': 'on my way',
 'ppl': 'people',
 'rn': 'right now',
 'sry': 'sorry',
 'tmrw': 'tomorrow',
 'txt': 'text',
 'wknd': 'weekend',
 'xoxo': 'hugs and kisses',
 'ya': 'you',
 'yup': 'yes',
 'nah': 'no',
 'fav': 'favorite',
 'sec': 'second',
 'mins': 'minutes',
 'congrats': 'congratulations',
 'gonna': 'going to',
 'wanna': 'want to',
 'gotta': 'got to',
 'lemme': 'let me',
 'tho': 'though',
 'thru': 'through',
 'yolo': 'you only live once',
 'fomo': 'fear of missing out',
 'tgif': "thank god it's friday",
 'wtf': 'what the fuck',
 'wth': 'what the hell',
 'idc': 'i do not care'}

In [33]:
def chat_conversion(text):
    words = text.split()
    new_words = []
    for word in words:
        if word in chat_words:
            new_words.append(chat_words[word])
        else:
            new_words.append(word)
    return ' '.join(new_words)

In [34]:
text = "hru btw idk"
print(chat_conversion(text))

how are you by the way i do not know

In [36]:
from textblob import TextBlob

In [37]:
incorrect_text = "I havv goood speling"
corrected_text = TextBlob(incorrect_text).correct()
print(corrected_text)

I have good spelling

In [39]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [40]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
print(stop_words)

{'does', 'her', "aren't", 'during', "hasn't", "they've", 've', 'below', 'between', "mustn't", 'you', 'there', 'theirs', 'i', 'about', 'having', 'off', 'more', 'should', "didn't", 'into', 'myself', 'over', 'yourself', 'd', "shouldn't", 'than', "it's", "she's", 'such', "i've", 'if', 'do', 'very', 'that', 'it', "weren't", 'don', 'these', 'a', 'mustn', 'were', "we'd", 'doesn', "he's", 'why', 're', 'y', "doesn't", "wouldn't", 'the', 'won', 'in', 'ain', 'how', 'where', 'hasn', 'when', "that'll", 'while', 'they', 'what', "it'd", 'under', "you're", 'my', 'of', "i'd", 'been', 'with', 'so', "should've", 'by', 'same', 'then', "she'll", 'who', 'doing', 'before', 'be', 'his', 'other', 'few', 'am', 'just', 'on', "wasn't", 'whom', "you'll", 'against', 'shan', "we're", 'mightn', 'all', 'itself', 'or', 'our', 'too', 'did', 'hadn', 'needn', 'didn', 'here', 'has', 'me', 'yours', "he'd", 'above', 'but', 'hers', 'through', "they'll", 'weren', "isn't", 's', "they're", 'again', 'any', "couldn't", 'until', "i'll", 'wasn', 'have', "mightn't", 'haven', 'their', 'out', 'ma', 'your', 'to', 'those', 'own', 'both', "you'd", 'couldn', 'its', 'only', 'm', 'most', 'no', 'she', 'shouldn', 'an', "haven't", 'once', 'ours', 'some', 'down', 'wouldn', 'o', "she'd", "we'll", 'is', 'at', "we've", 'up', 'which', 'ourselves', 't', "he'll", 'now', "you've", 'are', 'as', 'can', 'each', "hadn't", 'isn', "needn't", 'he', "they'd", 'herself', "i'm", "shan't", "won't", 'himself', 'and', 'was', 'we', "don't", 'had', 'this', 'yourselves', 'll', 'not', 'after', "it'll", 'for', 'will', 'him', 'further', 'themselves', 'from', 'because', 'being', 'aren', 'nor', 'them'}

In [42]:
def remove_stopwords(text):
    new_text=[]
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x=new_text[:]
    new_text.clear()
    return ' '.join(x)

In [43]:
text = "I am learning NLP from CampusX"

print(remove_stopwords(text))

I  learning NLP  CampusX

In [44]:
def remove_emojis(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [45]:
remove_emojis("Hello 😊! How are you? 🚀")

'Hello ! How are you? '

In [48]:
import emoji
print(emoji.demojize("Hello 😊! How are you? 🚀"))

Hello :smiling_face_with_smiling_eyes:! How are you? :rocket:

In [50]:
##word tokenization
sentence = "Hello, how are you doing today?"
tokens = sentence.split()
print(tokens)

['Hello,', 'how', 'are', 'you', 'doing', 'today?']

In [52]:
# sentence tokenization
text = "I am going home. It is a beautiful day. I hope you're doing well."
text.split('.')

['I am going home', ' It is a beautiful day', " I hope you're doing well", '']

In [53]:
# problems with split() method
sentence = "Hello, how are you doing today?"
tokens = sentence.split()
print(tokens)

['Hello,', 'how', 'are', 'you', 'doing', 'today?']

## 2. Regular Expression

In [59]:
import re
sent3=" How are you doing today?"
tokens = re.findall(r"\w+", sent3)
print(tokens)

['How', 'are', 'you', 'doing', 'today']

In [62]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [68]:
import nltk

nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [69]:
sent4= "Hello, how are you doing today? I hope you're doing well."
print(word_tokenize(sent4))

['Hello', ',', 'how', 'are', 'you', 'doing', 'today', '?', 'I', 'hope', 'you', "'re", 'doing', 'well', '.']

In [70]:
text = "Hello, how are you doing today? I hope you're doing well. NLP is interesting."

print(sent_tokenize(text))

['Hello, how are you doing today?', "I hope you're doing well.", 'NLP is interesting.']

In [71]:
sent5="my gmail is example@gmail.com"
print(word_tokenize(sent5))

['my', 'gmail', 'is', 'example', '@', 'gmail.com']

In [74]:
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("Hello, how are you doing today? I hope you're doing well.")
for token in doc:
    print(token.text)

Hello
,
how
are
you
doing
today
?
I
hope
you
're
doing
well
.

In [75]:
doc=nlp("my gmail is example@gmail.com")
for token in doc:
    print(token.text)

my
gmail
is
example@gmail.com

In [76]:
from nltk.stem import PorterStemmer

In [77]:
ps=PorterStemmer()
def stem_word(word):
    return " ".join([ps.stem(w) for w in word.split()])

In [78]:
sample_text = "running runner runs"
print(stem_word(sample_text))

run runner run

In [79]:
text = """
The boys were playing football in the playground. They played for several hours
and enjoyed the game. One of the players was running very fast while another
player runs slowly. The coach was motivating and encouraging the team members.

Many students are studying machine learning and they studied different algorithms
last semester. Some students study every day while others are interested in
researching advanced topics. Researchers have researched artificial intelligence
for many years.

The workers worked hard and are working on improving the system. The company
improves its products continuously and has improved customer satisfaction.
Several improvements were suggested during the meeting.

The programmer writes code every day. He wrote a program yesterday and is writing
another program today. Many programmers enjoy programming because it helps them
develop problem-solving skills.

Children are caring for animals and cared for them during the holidays. Their
parents care deeply about animal welfare. Caring people often volunteer in
different organizations.

The teacher teaches mathematics in school. She taught algebra last year and is
teaching geometry this year. Her teaching methods are appreciated by the students.
"""
print(stem_word(text))

the boy were play footbal in the playground. they play for sever hour and enjoy the game. one of the player wa run veri fast while anoth player run slowly. the coach wa motiv and encourag the team members. mani student are studi machin learn and they studi differ algorithm last semester. some student studi everi day while other are interest in research advanc topics. research have research artifici intellig for mani years. the worker work hard and are work on improv the system. the compani improv it product continu and ha improv custom satisfaction. sever improv were suggest dure the meeting. the programm write code everi day. he wrote a program yesterday and is write anoth program today. mani programm enjoy program becaus it help them develop problem-solv skills. children are care for anim and care for them dure the holidays. their parent care deepli about anim welfare. care peopl often volunt in differ organizations. the teacher teach mathemat in school. she taught algebra last year and is teach geometri thi year. her teach method are appreci by the students.

In [82]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...

True

In [84]:
import nltk
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()
sentence = "The boys were playing football in the playground."
punctuations="?:!.,;"
sentence_words=word_tokenize(sentence)
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

sentence_words
print("{0:20} {1:20} ".format("Word", "Lemma"))
for word in sentence_words:
    print("{0:20} {1:20}".format(word, wordnet_lemmatizer.lemmatize(word,pos='v')))

Word                 Lemma
The                  The
boys                 boys
were                 be
playing              play
football             football
in                   in
the                  the
playground           playground

In [1]:
!pip install spacy

Requirement already satisfied: spacy in D:\NLP\venv\Lib\site-packages (3.8.13)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in D:\NLP\venv\Lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in D:\NLP\venv\Lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in D:\NLP\venv\Lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in D:\NLP\venv\Lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in D:\NLP\venv\Lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in D:\NLP\venv\Lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in D:\NLP\venv\Lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in D:\NLP\venv\Lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in D:\NLP\venv\Lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in D:\NLP\venv\Lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in D:\NLP\venv\Lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in D:\NLP\venv\Lib\site-packages (from spacy) (0.26.7)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in D:\NLP\venv\Lib\site-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in D:\NLP\venv\Lib\site-packages (from spacy) (2.4.6)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in D:\NLP\venv\Lib\site-packages (from spacy) (2.34.2)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in D:\NLP\venv\Lib\site-packages (from spacy) (2.13.4)
Requirement already satisfied: jinja2 in D:\NLP\venv\Lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in D:\NLP\venv\Lib\site-packages (from spacy) (82.0.1)
Requirement already satisfied: packaging>=20.0 in D:\NLP\venv\Lib\site-packages (from spacy) (26.2)
Requirement already satisfied: annotated-types>=0.6.0 in D:\NLP\venv\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in D:\NLP\venv\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in D:\NLP\venv\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in D:\NLP\venv\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in D:\NLP\venv\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in D:\NLP\venv\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in D:\NLP\venv\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in D:\NLP\venv\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.5.20)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in D:\NLP\venv\Lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: colorama in D:\NLP\venv\Lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: shellingham>=1.3.0 in D:\NLP\venv\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in D:\NLP\venv\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in D:\NLP\venv\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in D:\NLP\venv\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in D:\NLP\venv\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.1)
Requirement already satisfied: httpx>=0.24.0 in D:\NLP\venv\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in D:\NLP\venv\Lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in D:\NLP\venv\Lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in D:\NLP\venv\Lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in D:\NLP\venv\Lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in D:\NLP\venv\Lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in D:\NLP\venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in D:\NLP\venv\Lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in D:\NLP\venv\Lib\site-packages (from jinja2->spacy) (3.0.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import spacy

In [5]:
nlp=spacy.load("en_core_web_sm")
doc=nlp(u" I will google about facebook and twitter")

In [6]:
doc.text

' I will google about facebook and twitter'

In [9]:
doc[-1]

twitter

In [10]:
doc[2].pos_

'AUX'

In [11]:
spacy.explain(doc[2].pos_)

'auxiliary'

In [13]:
for word in doc:
    print(word.text,"------->",  word.pos_, word.tag_, spacy.explain(word.tag_))

  -------> SPACE _SP whitespace
I -------> PRON PRP pronoun, personal
will -------> AUX MD verb, modal auxiliary
google -------> VERB VB verb, base form
about -------> ADP IN conjunction, subordinating or preposition
facebook -------> NOUN NN noun, singular or mass
and -------> CCONJ CC conjunction, coordinating
twitter -------> NOUN NN noun, singular or mass

In [14]:
doc2=nlp(u"I read book on history")
for word in doc2:
    print(word.text,"------->",  word.pos_, word.tag_, spacy.explain(word.tag_))

I -------> PRON PRP pronoun, personal
read -------> VERB VBP verb, non-3rd person singular present
book -------> NOUN NN noun, singular or mass
on -------> ADP IN conjunction, subordinating or preposition
history -------> NOUN NN noun, singular or mass

In [16]:
doc3=nlp(u"I have read a book on history")
for word in doc2:
    print(word.text,"------->",  word.pos_, word.tag_, spacy.explain(word.tag_))

I -------> PRON PRP pronoun, personal
have -------> AUX VBP verb, non-3rd person singular present
read -------> VERB VBN verb, past participle
a -------> DET DT determiner
book -------> NOUN NN noun, singular or mass
on -------> ADP IN conjunction, subordinating or preposition
history -------> NOUN NN noun, singular or mass

In [17]:
doc4=nlp(u"The quick brown fox jumps over the lazy dog")

In [18]:
from spacy import displacy
displacy.render(doc4, style='dep', jupyter=True)

In [19]:
options = {"distance": 90, "compact": True, "color": "blue", "bg": "white", "font": "Source Code Pro"}
displacy.render(doc4, style='dep', jupyter=True, options=options)